name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        env:
          NODE_VERSION: "16"
        with:
          node-version: "${{ env.NODE_VERSION }}"
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Setup pnpm cache
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ env.NODE_VERSION }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-${{ env.NODE_VERSION }}-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: frontend
      - name: Lint
        run: pnpm lint
        working-directory: frontend
      - name: Test
        run: pnpm test
        working-directory: frontend
      - name: Check docs updated
        run: |
          pnpm build:docs
          if [ "$(git diff --stat)" != "" ]; then echo "Docs were not updated"; exit 1; else echo "Docs are up-to-date"; fi
        working-directory: frontend

